### ISSUE TITLE
Ryan's todo list

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#1014]
### Roadmap
- [ ] Implement Google Analytics tracking for features (and functionality) added in `1.6`.  ( #774)
- [ ] Fix discovery refresh project list spindicator not working (#931, #1010)
- [x] Fix Travis CI builds failing, due to bad ESLint configuration. (#1011)
- [x] Remove beta from project share URLs. ( #1012)
- [ ] Fix green arrow not dismissing keyboard in Project Settings view. (#847)
- [ ] Improve project sharing copy. (#946)
- [ ] Remove pull-to-refresh in Project Settings view. (Dependent on #931, #841)
- [ ] Layout road map to implementing 
- [ ] Setup and configure AWS device farm, and implement unit testing for the app.
- [ ] Clean up issue tracker, close old (or fixed) tickets, reorganize milestone assignments.
- [ ] Fix no selected animation for setting text style (#477)
- [ ] Fix back button not dismissing modal in Make view (#808)
