### ISSUE TITLE
API - Batch requests to the API

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#183]
This issue has been migrated from mozilla/webmaker-android#2179.

It was originally written by [LauraReynal](https://api.github.com/users/LauraReynal) on Fri Jun 12 2015 and had the following description:

> It has been a blocker to create content with people - a large number just gave up. 
> We had good conditions and were on stable wifi. 
> 
> here is a screencast : 
> https://drive.google.com/drive/folders/0B-1AZgKn5Nc7YldzMUtlOFhUVE0/0B0X05aIHuAbeQkphUkdGeHRjdjQ
> 
> I'm happy to try different suggestions, but it's been the same experience for users, no matter phones and versions. 
> cc/ **@****thisandagain** **@****k88hudson** 

On Fri Jun 12 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Can you give a another look on the production APK today? I'd love to see how performance feels from the real datacenter.

On Fri Jun 19 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Depends on https://github.com/mozilla/api.webmaker.org/issues/76

**Comment by Pomax** [comment]
A stub for the idea as expressed in (not quite true) code:

# JAVA SIDE: API mirror
```
    public class APIMirror {
      public APIMirror() {
        ...
      }

      @JavaScript
      public void functionFromAPIJS1(...) {
        do things async here, and when a result comes in, serialize to JSON and add to a queue
        as:

        -> queue.add("function1", JSONSerialize(resultData));

        Every time that happens, Android can call a global JS function to initiate a "doing
        the processing" on the javascript side:

        -> callGlobalOnActivePageContext(" processAPIQueue(" + JSONSerialize(queue) + "); ");
      }

      @JavaScript
      public void functionFromAPIJS2(...) {
        ... 
        -> queue.add("function2", JSONSerialize(resultData));
        -> callGlobalOnActivePageContext(" processAPIQueue(" + JSONSerialize(queue) + "); ");
      }
    }
```

# JAVA SIDE: platform class
```
    public class Platform {
      APIMirror api = new APIMirror();
      ...
      @JavaScript
      APIMirror getAPI() {
        return api;
      }
      ...
    }
```

#JAVASCRIPT SIDE: api.js
```
    var javaApi = window.platform.getAPI();
    var apiqueue = require('./lib/apiqueue.js');
    module.exports = {
      function1: function(..., callback) {
        javaApi.functionFromAPIJS1(...);
        apiqueue.push("function1", callback)
      },

      function2: function(..., callback) {
        javaApi.functionFromAPIJS2(this,arguments)
        apiqueue.push("function2", callback)
      },

      ...
    };
```

#JAVASCRIPT SIDE: apiqueue.js
```
    var handlers = {};
    module.exports = {
      push: function(type, handler) {
        if(!handlers[type]) {
          handlers[type] = [];
        }
        handlers[type].push(handler);
      }
    };
```

#JAVASCRIPT SIDE: special handler global function that android can trigger
```
    var apiqueue = require('./lib/apiqueue');

    function processAPIQueue(jsonPayload) {
      var data = JSON.parse(jsonPayload);
      data.forEach(function(item) {
        var type = item.type;
        var data = item.data;
        // get all callbacks for this type
        var callbacks = apiqueue[type];
        callbacks.forEach(function(callback) {
          // try to send off the callback for handling
          try {
            callback(data);
            // and then invalidate that specific callback
          } catch (e) { 
            ...
          }
        });
      });
    }
```

**Comment by Pomax** [comment]
putting in some plan-of-attack steps:
- [x] make sure that we can call the "bulk" API endpoint correctly

The API server needs to be on cade's `cadecarios/bulk` branch until PR https://github.com/mozilla/api.webmaker.org/pull/118 is merged into dev/master.

The API server will run on `http://localhost:2015`, which can be exposed to actual physical Android devices via a LAN: if your computer is running on LAN ip `192.168.0.1` for instance, the `webmaker-core` bundling can be told to use that IP for its API endpoint by, in the `webmaker-android` project, creating an `.env` file with content `API_URI=http://192.168.0.1:2015`. Running the webmaker-android bundling via `npm start` will then yield a new bundle that will use your local API instead of the development heroku instance.
- [x] refactor one API creation route to run over the bulk endpoint - I chose the "create a project" operation

The project creation operation has the benefit of being a genuine bulk operation in that it needs to a) create a new project and b) create a new, empty page inside that project before it gets loaded up for the user. See https://github.com/Pomax/webmaker-core/blob/bulk/src/pages/make/make.jsx#L61-127
- [ ] refactor the rest of the code so that all project/page/element creation and updates run over the bulk endpoint
  - [x] cover page and element
    - [x] page <-> element
    - [x] element <-> tinker mode
    - [x] element <-> "pick link destination"
    - [x] element-on-page <-> "pick link destination"
  - [ ] cover project **filed as follow up https://github.com/mozilla/webmaker-core/issues/452**
- [x] take one route, and swap the processing order from `[update]->[api]->[result]->[continue]` to `[update] -> [immediately continue] + [api] -> [result] -> local update` to remove the waiting period.
- [x] move the `[api]` step into its own queue handler
- [ ] progressively update more routes **filed as follow up https://github.com/mozilla/webmaker-core/issues/452**
- [ ] clean up the code *\* filed as follow up https://github.com/mozilla/webmaker-core/issues/451**

**Comment by thisandagain** [comment]
Closing and tracking in follow-up tickets.
