### ISSUE TITLE
Pomax' QA List

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#494]
In order to close this bug, go through the follow scripts:
1. [Creating an Account & Signing In](https://github.com/mozilla/webmaker-core/issues/395)
2. [Creating & Deleting Projects](https://github.com/mozilla/webmaker-core/issues/397)

File any bugs as separate tickets, just remember to assign the `QA` label to the issue so it can get triaged accordingly.

Let's do this!

**Comment by Pomax** [comment]
# Creating an Account & Signing In

**Sign up**
- [x] open the app (or log out from the 'MAKE' tab, if already signed in)
- [x] make sure you are on the screen that says the equivalent of "Join Webmaker" on the button at the bottom
- [x] tap the "Terms" and "Privacy Policy" links at the very bottom
- [x] enter an invalid username by adding a @ in the Username field, check the error message you see
- [x] change to a valid username
  - why can names only be 1-20 characters? https://github.com/mozilla/webmaker-core/issues/502
- [x] start typing an email address, check the message you see
- [x] start typing a password, check the message you see
  - **password not strong enough** notice does not show until after the user tries to join, with the message "password not string enough". As a regular user, I have on idea what that means. https://github.com/mozilla/webmaker-core/issues/499
  - typing a new password does not clear the "not strong enough" error, confronting the user with two errors. https://github.com/mozilla/webmaker-core/issues/500
  - why do we demand letters and numbers, when we're already testing password strength? There is no reason to insist on at least 1 number if we reject easy to guess passwords anyway. https://github.com/mozilla/webmaker-core/issues/501
- [x] press 'Join Webmaker'
  - using a non-resolving email address does not seem to affect the join process. https://github.com/mozilla/webmaker-core/issues/503

**Sign in**
- [x] open the app (or log out from the 'MAKE' tab, if already signed in)
- [x] make sure you are on the screen that says the equivalent of "Sign in" on the button at the bottom
- [x] tap the "Reset Password" link
- [x] enter an invalid username and password, press Sign In
  - impossible usernames are not flagged as invalid on the "sign in" view, only on the "join webmaker" view. https://github.com/mozilla/webmaker-core/issues/546
- [x] check the error message you see
  - error does not disappear when the user corrects their username or password https://github.com/mozilla/webmaker-core/issues/504
- [x] enter a valid username and password, press sign in

**Comment by Pomax** [comment]
# Creating & Deleting Projects
- [x] Open the app and tap the Make tab, which displays the Make view

**Make View**
- [x] you see your username displayed at the top of the view
- [x] tap the "+ Create a Project" button, you will enter the Project view

**Project View**
- [x] you are in the map view of a project with a single page
  - [x] the page is selected (there is a blue border around it)
- [x] tap the triple dot menu in the top right corner, and pick "settings".
- [x] you will enter the Project Settings view

**Project Settings**
- [x] the project title is "My project"
  - why can I only have 25 letters for a project? This seems arbitrarily low. https://github.com/mozilla/webmaker-core/issues/505
- [x] tap the project title to start editing it
- [x] you will see a keyboard
- [x] as you edit the name, the character indicator below the title keeps track of your character count
- [x] change the name to something that is less than or equal to 25 characters
- [x] tap the green arrow on the bottom of the keyboard, you will finish editing
  - the only green arrow on my keyboard is where the "enter" etc normally lives. Pressing it it does nothing. https://github.com/mozilla/webmaker-core/issues/506
- [x] edit the name again, then tap anywhere outside of the name or keyboard to finish editing
- [x] edit the name again, and make the name longer than 25 characters
- [x] the character count indicator and underline should turn red
- [x] tap outside of the project name to finish editing
  - I can save projects with a title that is "too long"? Is the red not an error? If not, why is even red? Or there at all? https://github.com/mozilla/webmaker-core/issues/507
- [x] tap the back arrow, the view switches to the Project view
- [x] go back to the project settings view
- [x] the project title is the same as the last time you saw it in this view
  - The character indicator is still a "more than 25" value, but there is no red warning coloring. https://github.com/mozilla/webmaker-core/issues/508
- [x] Tap the back arrow to return to the Project view
- [x] tap the back arrow again, you return to the Make view

**Make View**
- [x] the project you just created is at the top of the list of your projects, just below the Create Project button
- [x] tap the three-dot menu on that project, the Share & Delete menu opens
- [x] tap "Delete", the Make view refreshes and your project is no longer there
  - it does not. No refresh occurs. https://github.com/mozilla/webmaker-core/issues/457

**Extra test**
- [x] make a project, call it "Project 1", then go back to the make view
- [x] make another project, call it "Project 2", then go back go the make view
- [x] "Project 2" is listed above "Project 1".

**Comment by xmatthewx** [comment]
:boom: :zap: speedy and thorough

**Comment by vazquez** [comment]
Thanks so much @Pomax!

You get the victory dance GIF!

![](http://media.giphy.com/media/kZzQfQ3ld9l8k/giphy.gif)

**Comment by xmatthewx** [comment]
cc @flukeout to see where it all began
