### ISSUE TITLE
Kate's QA List

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#495]
In order to close this bug, go through the follow scripts:
1. [Image Element](https://github.com/mozilla/webmaker-core/issues/399)
2. [Project Editing Basics](https://github.com/mozilla/webmaker-core/issues/398)

File any bugs as separate tickets, just remember to assign the `QA` label to the issue so it can get triaged accordingly.

Oh yeah!

![](http://38.media.tumblr.com/ad087ad896210571ea890d03d935751b/tumblr_no1hu8LyDG1uv6utjo1_500.gif)

**Comment by k88hudson** [comment]
- [x] open one of your existing projects or create a new one
- [x] edit one the pages
- [x] tap the plus icon at the bottom of the page add an image element to the page
  - [x] an image appears in the center of the page (it can be one of many starter images)
  - [x] the image is selected, it has a blue dashed border
  - [x] there is a garbage icon, a plus icon, and a paintbrush icon at the bottom of the page

**Moving the Image**
- [x] drag the image around the page, it moves with your finger
- [x] pinch the image to make it larger and smaller
- [x] rotate the image both directions using two-finger gesture

**Image Options**
- [x] tap the pencil icon to enter the Options view
- [x] change each of the available settings, the preview at the top of the page updates as you do so
  - [x] Opacity
  - [x] Border color
  - [x] Border width
  - [x] Corner radius
- [x] once you've made changes, tap the back arrow in the header to return to the Page view
- [x] the changes you made are reflected in the Page view
- [x] tap the pencil icon to enter the Options view again
  - [x] the changes you made to the image are reflected in the UI
- [x] tap the Change Image button, you see two options Take Photo & Camera Gallery
  - [x] tap Take Photo and complete the process, the image changes as expected
- [x] tap the Change Image button, you see two options Take Photo & Camera Gallery
  - [x] tap Camera Gallery and choose a photo, the image changes as expected
- [x] tap the back arrow to return to the Page view, the image is the same as the one you selected from the phone gallery

**Deleting the Image**
- [x] tap the Garbage icon, the image element is deleted

**Comment by k88hudson** [comment]
- [x] create a new project, or open an existing one
- [x] you will see the map view of the project, centered on one of the pages
- [x] the blue header says "Project"
- [x] the centered page is selected
- [x] the pencil and trash icons are visible below the page
- [x] dragging the view to pan around the project view
- [x] pinching the view zooms the view in and out
- [x] pan to a place where there is an empty space with a "+" icon
- [x] tap the plus icon, a new blank page will appear in that space
  - [x] the view shifts to place the new page in the center of the view
  - [x] the new page is selected (it has a blue border)
- [x] tap a different page in the project, the view shifts to that page and that page becomes selected
- [x] tap the trash icon, the selected page is deleted
  - [x] there is now a "+" icon where the page used to be

**Adding Elements**
- [x] tap any page in the Project view page to select it
- [x] tap the pencil icon, the view will change to the Page view
- [x] there is a plus icon at the bottom of the screen
- [x] tap the plus icon, the view becomes dark and three new icons are visible
- [x] tap the first icon to add a text element
- [x] repeat the process to add an image element, and a button element
- [x] tap the back arrow, the view returns to the zoomed-out Project view
- [x] the page you were just editing is centered
  - [x] the elements you added to the page are visible, and are in the same position

**Comment by k88hudson** [comment]
@vazquez looks good!

**Comment by xmatthewx** [comment]
:heavy_check_mark: :ballot_box_with_check:  :white_check_mark:  incredible. so many checkmarks!

**Comment by vazquez** [comment]
Thanks so much Kate!

![](http://media.giphy.com/media/11p1apCPqM7WEw/giphy.gif)

**Comment by xmatthewx** [comment]
cc @flukeout to witness the thrill
