### ISSUE TITLE
Gavin's QA List

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#496]
In order to close this bug, go through the follow scripts:
1. [Text Element](https://github.com/mozilla/webmaker-core/issues/400)
2. [Viewing a Project](https://github.com/mozilla/webmaker-core/issues/396)

File any bugs as separate tickets, just remember to assign the `QA` label to the issue so it can get triaged accordingly.

This is best done with some sweet music playing.

![](http://media.giphy.com/media/3L8vh5iwVC1eU/giphy.gif)

**Comment by gvn** [comment]
- [x] open one of your existing projects or create a new one
- [x] edit one the pages
- [x] tap the plus icon at the bottom of the page add a text element to the page by tapping the "Aa" icon
  - [x] a text element appears in the center of the page and contains some text
  - [ ] the text is selected, it has a blue dashed border - _Already a ticket open for this..._
  - [ ] there is a garbage icon, a plus icon, and a paintbrush icon at the bottom of the page
- [x] drag the text around the page, it moves with your finger
- [x] pinch the text to make it larger and smaller
- [x] rotate the text using a two-finger gesture, in both directions
- [x] tap the pencil icon to enter the Options view
- [x] change each of the available settings, the preview at the top of the page updates as you do so
  - [x] Font
  - [x] Color
  - [x] Text Style
- [x] once you've made changes, tap the back arrow in the header to return to the Page view
- [x] the changes you made are reflected in the Page view
- [x] tap the pencil icon to enter the Options view again
  - [x] the changes you made to the text element are reflected in the UI
- [x] tap the Edit Text button to enter text editing mode
- [x] you can edit the text by using the keyboard
- [x] tap the Done button to finish editing text
- [x] edit the text again and tap the green arrow on the keyboard to finish editing
- [x] tap the back arrow to return to the Page view
- [x] the text element has the text that you specified
- [x] tap the Garbage icon, the text element is deleted

**Comment by gvn** [comment]
- [x] Open the app and tap the Discover tab, which opens the Discover view

**Discover View**
- [x] In the Discover view you see a list of projects. Each projects includes...
  - [x] a title
  - [x] a preview image
  - [x] an author (indicated in blue)
- [x] scroll up and down to view additional projects
- [x] tap on any project in the Discover view, it will open

**Project Play Mode**
- [x] when the project opens, the header title is "Play"
- [x] you see a grid of pages
  - [x] pinch to zoom in and out
  - [x] drag to pan the view
- [x] tap a page to enter the Page view

**Page Vie**
- [x] In the Page view, you see the page you tapped previously, but zoomed in
- [x] there are arrows on the edge of the page that point to any adjacent pages
- [x] tapping an arrow moves the view to the adjacent page in that direction
- [ ] swiping the page in the direction of any of the arrows also moves the view to the adjacent page 
  - [ ] the view animates to the adjacent page smoothly
- [ ] swipe in a direction where there isn't an adjacent page, the view will not move **Swiping is disabled right meow**
- [ ] tap the back button in the header to zoom back out to the Project view - **This goes back to the Discover view**

**Project View**
- [x] the Project View is centered on the page you were just viewing
- [x] tap the menu (⋮) to reveal the share option
- [x] tap Share option to see a list of applications
- [x] tap anywhere to cancel
- [x] tap the back to exit the project and return to Discover mode

**Comment by gvn** [comment]
"tap the back button in the header to zoom back out to the Project view"

Has this functionality changed, or is this a bug? @thisandagain @xmatthewx

**Comment by xmatthewx** [comment]
That was the oringal plan @gvn, but the android header was a beast we never slayed. It's a big task, so we should review the spec based on things we've learned before we dive into that https://github.com/mozilla/webmaker-core/issues/46

**Comment by gvn** [comment]
Ah, got it. Thanks!

**Comment by vazquez** [comment]
@gvn I wronged you of a congratulatory GIF

![](http://media.giphy.com/media/UkQOjabv89N0A/giphy.gif)

**Comment by gvn** [comment]
![bizness](https://cloud.githubusercontent.com/assets/206379/9281708/d70405de-427b-11e5-8f51-552b21c9479e.gif)

**Comment by xmatthewx** [comment]
cc @flukeout to enjoy the fruits of his labor

**Comment by flukeout** [comment]
Is that @gvn up on a cloud there?!

**Comment by gvn** [comment]
Yeah! I think it's "The Cloud" that everyone is always talking about!
