### ISSUE TITLE
Curate conversations with UX designers to learn about online communities 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-core#579]
Hey Team, 

In order to start thinking and learning about online communities, let's reach out to UX designers of product we love and want to benchmark. Hopefully, they will be able to dedicate some time to talk to us and answer our questions :) 

This would be part of a broader research project to understand what community features would enhance Webmaker, Teach, our learning products and the broader Mozilla community. 

_Goal_: Learn about different models of online communities

_Task_ : 
- [x] Collect ideas of who you would like to talk to
- [ ] Reach out to people 
- [ ] Schedule conversations, and document 

Can you please add in this ticket people or products you would want to talk to? Feel free to tag a friend in this ticket :fried_shrimp: :dancer: :dancers: 

![where is that turkey](https://cloud.githubusercontent.com/assets/8261945/9406454/7a0178d0-47f8-11e5-8fea-f9eb2ece9553.gif)

@k88hudson @gvn @xmatthewx @flukeout @cadecairos @ashleygwilliams @vazquez @sabrinang @thisandagain @jbuck @Pomax @cassiemc @simonwex @lovegushwa @ryanw-se @errietta 
@amirad @thornet @secretrobotron @davidascher @omnignorant @adamlofting

**Comment by lauradereynal** [comment]
some ideas 
- Pinterest 
- Quora 
- Tumblr 
- P2PU
- Medium 
- Scratch 
- Scratch ED 
- Edmodo
- PicCollage 
- WattPad 
- DuoLingo
- Instagram 
- Snapchat 
- Canva

**Comment by lauradereynal** [comment]
- Open Ideo 
- Ashoka changemakers
- Wikipedia 
- Teach for India
- Skillshare 
- KickStarter 
- MakerFair / MakerED

**Comment by lauradereynal** [comment]
- Youtube 
- Minecraft forums / Planet Minecraft 
- Reddit

**Comment by thornet** [comment]
<3 this thread and count me in. Have been having similar research conversations already with P2PU and the Scratch team. 
- Github

For an educator online community, I also suggest: 
- http://educatorinnovator.org/clmooc/

Others to look at, more from a social action and advocacy angle: 
- 350.org
- Fight for the Future: https://www.fightforthefuture.org/

And for learning about online communities in non-Western countries: 
- WeChat: http://www.ethanzuckerman.com/blog/2013/06/02/wechat-learning-from-the-chinese-internet/ and http://www.mandarinpathways.org/wechat-for-education-chinese-teachers-connecting-globally/
- Telegram: https://telegram.org/
- Mobile for development case studies: http://techpresident.com/news/wegov/25162/report-what-can-mobile-do-you (a lot with SMS)

And doing social annotation: 
- https://hypothes.is/

And doing good secure, mobile online communication that's well designed: 
- https://whispersystems.org/

**Comment by edrushka** [comment]
- [watsi](https://watsi.org/)

**Comment by cassiemc** [comment]
I'd suggest whittling down the list and digging deep with one or two, @laurad, depending on your availability or how you plan to tackle this (are lots of people tackling?). Feel like the real value would be in having a shared conversation and understanding. Maybe we could even find a team local to wherever the next Webmaker and Teach team work weeks are to do a skillshare similar to the Fundraising team's day with Wikimedia during their work week.

**Comment by lauradereynal** [comment]
Good point @cassiemc :+1: 
For now Im just collecting ideas, so that we dont miss an important one. But I agree on few and deep rather than large and surface :)

**Comment by amirad** [comment]
Some others:
P2PU
Shopify
Medium
Edmodo
LinkedIn
Khan Academy
Coursera
BBC
Do Something
Good

**Comment by xmatthewx** [comment]
Pew published an interesting [report on mobile etiquette](http://www.pewinternet.org/2015/08/26/americans-views-on-mobile-etiquette/). In social settings (IRL), some people use their mobile to disengage or connect with people elsewhere. More activity, however, is to support the social gathering itself. 

I'm curious how existing digital platforms support/disrupt this behavior. For example, Instagram and Tinder are more conducive to group conversations than Twitter or other dating apps. How can Webmaker connect with this common behavior?

**Comment by xmatthewx** [comment]
It'd be good to categorize the list of platforms, and then target a few representative examples. I wonder which ones succeed at small to medium scale, without an expectation or need to reach kabillions. 

Meetup
Wordpress.org
We Heart It 
Good Reads
Processing

**Comment by xmatthewx** [comment]
Here's a looooong list the team made back in February: https://etherpad.mozilla.org/toolbenchmarks
