### ISSUE TITLE
implement hashtags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#772]
Involves a few different chunks of implementation:
- [x] tags & description API #727 
- [x] project descriptions #794 
  - [x] add description field to settings view
  - [x] display description on project card
- [x] tags #795
  - [x] build list view filtered by tag
- [x] wrap tags in description on project card with links #904 
- [ ] build tag "ads" for Discover #905

**Comment by vazquez** [comment]
I would just add a minor note that the project graphic in the Discover view will also change to a larger size. We've seen a lot of cropping mishaps as we can't intelligently know if where the content lies. 

<img width="239" alt="screenshot 2015-11-08 11 24 33" src="https://cloud.githubusercontent.com/assets/1119821/11020062/4dafa18e-860b-11e5-8b60-868d44b86eab.png">

**Comment by xmatthewx** [comment]
@vazquez - let's file the crop change as a new issue and delete from this thread.

**Comment by xmatthewx** [comment]
### projects settings
- add description field with helper text
  - "Include #hashtags to link other related projects in Discover"

![image](https://cloud.githubusercontent.com/assets/1119821/10436406/33fbefbc-70f4-11e5-9c0f-d6beb1eb39e9.png)

### project cards
- display project descriptions
  - wrap tags with links

![image](https://cloud.githubusercontent.com/assets/1119821/10436448/66f45274-70f4-11e5-989b-077390c2f8c8.png)

### list projects by tag
- link from tag leads to list view
- users can dismiss filter or tap Discover above to exit
- v1 does _not_ include search 

<img width="300" alt="screenshot 2015-11-13 12 17 45" src="https://cloud.githubusercontent.com/assets/53411/11152451/9652bb8a-8a00-11e5-8be0-e0a98b2dff03.png">

**Comment by gvn** [comment]
@xmatthewx – I'm wondering why the design is indicating a modal showing the description again. Isn't this kind of redundant? 

Also if the description gets too long the modal might not fit in the viewport.

**Comment by xmatthewx** [comment]
@gvn - Good question. We currently edit a `project title` directly on the settings view without a modal. @vazquez, let's update the comp and post it to #794.

**Comment by gvn** [comment]
Another question: Do we want to set a max length on project descriptions? I think we should...

**Comment by xmatthewx** [comment]
Done! Tag "ads" filed in #905.
