### ISSUE TITLE
Quality test 1.5 Beta Release

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#796]
1.5 Beta will be released soon. When that happens, we have a few people ready to help with Quality testing. I'm very excited to make this a team effort. 
- [x] Account Basics #803 
- [x] Viewing a Project #804
- [x] Creating & Deleting Projects #815
- [X] Project Editing Basics #814
- [x] Image Element #812
  - [x] Bug found, reported in #813
- [x] Button Element #811
- [x] Text Element #810

@debodirno - to get ready, take a look at the info on the [testing wiki page](https://github.com/mozilla/webmaker-core/wiki/Webmaker-Quality-Testing). From there, you'll see a link to sign up for Beta. After we launch, we can pick one of the templates for you to copy and use to guide your test and feedback.

@ioana-chiorean helped with the last round of tests and gave lots of great feedback on the app and on the testing templates. 

@vazquez is a designer on the project. He and I will help with any questions. You might also see comments from engineers @gvn @alanmoo and @ryanw-se. 

We will use the templates in the Wiki originally crafted by @flukeout. We will focus specifically on the new features listed here: https://github.com/mozilla/webmaker-core/issues/765#issuecomment-156539700

I will drop a new comment here after the release lands in the play store.  

:dancers: :rocket:

**Comment by xmatthewx** [comment]
Updated link to wiki page: https://github.com/mozilla/webmaker-core/wiki/Webmaker-Quality-Testing

**Comment by ioana-chiorean** [comment]
On your mark, get set... :runner:

**Comment by xmatthewx** [comment]
@ioana-chiorean & @debodirno – want to meet up on video sometime this week? I'd be glad to answer any questions and would love to hear about your interests as a contributor.

**Comment by debodirno** [comment]
How about Sunday?

**Comment by xmatthewx** [comment]
Ok team. Webmaker 1.5 Beta has landed in the play store! You should see an update available on your device now or in the next couple hours.

Pick a test from the [wiki page](https://github.com/mozilla/webmaker-core/wiki/Webmaker-Quality-Testing). When you open a ticket to start the test, drop a link to the new issue in this thread. That way, we can avoid duplicating each other's effort. Does that make sense? If you're on IRC, you can ping me (mattheww) in the webmaker channel with any questions. 

Thanks! :checkered_flag:

**Comment by ioana-chiorean** [comment]
> want to meet up on video sometime this week? 

Yes - I am in CET+1/UTC+2 now 

> Pick a test from the wiki page.

Will start some tasks/qa issues now

**Comment by ioana-chiorean** [comment]
@debodirno, @vazquez what phones and android versions did u guys used?

**Comment by vazquez** [comment]
@ioana-chiorean Nexus 5 running Android 6.0

**Comment by debodirno** [comment]
Moto E running Android 5.1

**Comment by xmatthewx** [comment]
@debodirno - what time zone are you in? Would it be possible to meet on a weekday? Or is that difficult?

**Comment by xmatthewx** [comment]
@ioana-chiorean - I am in Brooklyn, UTC-5. Would Thursday or Friday at 15:00 UTC work for you? Are you on Vidyo? Skype works for me as well. 

I aded device and version to the Quality test templates so we capture that in the future.

**Comment by debodirno** [comment]
I am in Kolkata, India. UTC +5:30

**Comment by ioana-chiorean** [comment]
@debodirno / @vazquez / @xmatthewx - Tomorrow morning (in 10h) in the office - if it is not to late - I can check on a 4.x device and an x86 Intel architecture phone. Also on a tablet. I have as personal only a Nexus 5/Android 6.0.

@xmatthewx - yes, both Thursday and Friday would work for me at 15UTC. Vidyo will work fine.

**Comment by xmatthewx** [comment]
Hi everyone. 1.5.1 Beta is now in the play store. It fixes a few of the bugs and quirks we found in 1.5. 

I don't think we need full tests. Play around with it to see if the fixes are good or if you notice anything else.  Thanks!

**Comment by xmatthewx** [comment]
Quality tests are complete. Let's continue to play with the app over the weekend with the plan to release on Monday.
